name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
      - name: Use cached node_modules
        uses: actions/cache@v2.1.3
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test --ci --coverage --maxWorkers=2
